### ISSUE TITLE
Error while building application

### ISSUE THREAD

**Issue by netixx** [Tanibox/tania-core#104]
Hello,

I have an error while building the application (npm):

This error in particular seems to repeat itself:
 ```
ERROR in ./resources/js/components/app.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/tania-core/node_modules/vue-loader/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/tania-core/node_modules/vue-loader/lib/index.js:67:22)
 @ ./resources/js/app.js 8:0-48 51:15-27
 @ multi ./resources/js/app.js
```

Here is the rest of the logs:
```
Hash: 92ff731e4713ae3323ec
Version: webpack 4.42.1
Time: 23006ms
Built at: 04/06/2020 5:07:31 PM
 33 assets
Entrypoint bundle = bundle.css bundle.487fefac8d60c8eb1225.js

ERROR in ./resources/js/components/app.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.10 (/tania-core/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.11 (/tania-core/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./resources/js/app.js 8:0-48 51:15-27
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/home.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.10 (/tania-core/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.11 (/tania-core/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./resources/js/router.js 13:13-39
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/auth/login.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.10 (/tania-core/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.11 (/tania-core/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./resources/js/router.js 19:13-45
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/components/error.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.10 (/tania-core/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.11 (/tania-core/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./resources/js/component.js 1:0-50 3:16-28 5:35-47
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/intro/farm.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.10 (/tania-core/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.11 (/tania-core/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./resources/js/router.js 28:13-45
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/farms/create.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.10 (/tania-core/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.11 (/tania-core/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./resources/js/router.js 55:13-47
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/intro/reservoir.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.10 (/tania-core/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.11 (/tania-core/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./resources/js/router.js 37:13-50
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/intro/area.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.10 (/tania-core/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.11 (/tania-core/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./resources/js/router.js 46:13-45
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/farms/reservoir.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.10 (/tania-core/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.11 (/tania-core/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./resources/js/router.js 73:13-50
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/farms/area.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.10 (/tania-core/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.11 (/tania-core/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./resources/js/router.js 91:13-45
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/farms/reservoirs.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.10 (/tania-core/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.11 (/tania-core/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./resources/js/router.js 64:13-51
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/farms/areas.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.10 (/tania-core/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.11 (/tania-core/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./resources/js/router.js 82:13-46
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/farms/crop.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.10 (/tania-core/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.11 (/tania-core/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./resources/js/router.js 109:13-45
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/tasks/task.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.10 (/tania-core/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.11 (/tania-core/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./resources/js/router.js 127:13-45
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/inventories/materials.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.10 (/tania-core/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.11 (/tania-core/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./resources/js/router.js 136:13-56
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/farms/crops.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.10 (/tania-core/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.11 (/tania-core/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./resources/js/router.js 100:13-46
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/farms/crop-notes.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.10 (/tania-core/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.11 (/tania-core/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./resources/js/router.js 118:13-51
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/settings/account.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.10 (/tania-core/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.11 (/tania-core/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./resources/js/router.js 145:13-51
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/components/app.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/tania-core/node_modules/vue-loader/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/tania-core/node_modules/vue-loader/lib/index.js:67:22)
 @ ./resources/js/app.js 8:0-48 51:15-27
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/home.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/tania-core/node_modules/vue-loader/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/tania-core/node_modules/vue-loader/lib/index.js:67:22)
 @ ./resources/js/router.js 13:13-39
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/auth/login.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/tania-core/node_modules/vue-loader/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/tania-core/node_modules/vue-loader/lib/index.js:67:22)
 @ ./resources/js/router.js 19:13-45
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/components/error.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/tania-core/node_modules/vue-loader/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/tania-core/node_modules/vue-loader/lib/index.js:67:22)
 @ ./resources/js/component.js 1:0-50 3:16-28 5:35-47
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/intro/farm.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/tania-core/node_modules/vue-loader/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/tania-core/node_modules/vue-loader/lib/index.js:67:22)
 @ ./resources/js/router.js 28:13-45
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/farms/create.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/tania-core/node_modules/vue-loader/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/tania-core/node_modules/vue-loader/lib/index.js:67:22)
 @ ./resources/js/router.js 55:13-47
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/intro/reservoir.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/tania-core/node_modules/vue-loader/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/tania-core/node_modules/vue-loader/lib/index.js:67:22)
 @ ./resources/js/router.js 37:13-50
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/intro/area.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/tania-core/node_modules/vue-loader/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/tania-core/node_modules/vue-loader/lib/index.js:67:22)
 @ ./resources/js/router.js 46:13-45
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/farms/reservoir.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/tania-core/node_modules/vue-loader/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/tania-core/node_modules/vue-loader/lib/index.js:67:22)
 @ ./resources/js/router.js 73:13-50
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/farms/area.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/tania-core/node_modules/vue-loader/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/tania-core/node_modules/vue-loader/lib/index.js:67:22)
 @ ./resources/js/router.js 91:13-45
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/farms/reservoirs.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/tania-core/node_modules/vue-loader/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/tania-core/node_modules/vue-loader/lib/index.js:67:22)
 @ ./resources/js/router.js 64:13-51
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/farms/areas.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/tania-core/node_modules/vue-loader/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/tania-core/node_modules/vue-loader/lib/index.js:67:22)
 @ ./resources/js/router.js 82:13-46
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/farms/crop.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/tania-core/node_modules/vue-loader/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/tania-core/node_modules/vue-loader/lib/index.js:67:22)
 @ ./resources/js/router.js 109:13-45
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/tasks/task.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/tania-core/node_modules/vue-loader/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/tania-core/node_modules/vue-loader/lib/index.js:67:22)
 @ ./resources/js/router.js 127:13-45
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/inventories/materials.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/tania-core/node_modules/vue-loader/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/tania-core/node_modules/vue-loader/lib/index.js:67:22)
 @ ./resources/js/router.js 136:13-56
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/farms/crops.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/tania-core/node_modules/vue-loader/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/tania-core/node_modules/vue-loader/lib/index.js:67:22)
 @ ./resources/js/router.js 100:13-46
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/farms/crop-notes.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/tania-core/node_modules/vue-loader/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/tania-core/node_modules/vue-loader/lib/index.js:67:22)
 @ ./resources/js/router.js 118:13-51
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js

ERROR in ./resources/js/pages/settings/account.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/tania-core/node_modules/vue-loader/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/tania-core/node_modules/vue-loader/lib/index.js:67:22)
 @ ./resources/js/router.js 145:13-51
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/sass-loader/dist/cjs.js!resources/sass/app.scss:
    Entrypoint mini-css-extract-plugin = *
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --mode production --progress --hide-modules`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-06T17_07_31_977Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ prod: `npm run production`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-06T17_07_33_173Z-debug.log

```

**Comment by Guigouu** [comment]
Same here

**Comment by Guigouu** [comment]
# Fixed: 
Miss match between vue-template-compiler and vue
`npm install vue-template-compiler@2.6.11 --save-dev`
`npm install vue@2.6.11 --save-dev`
`npm run dev`
you can also build with npm install 2.6.10 if needed

**Comment by wotnak** [comment]
This problem was caused by using npm and the fact that `package-lock.json` is missing from the repo. In which case npm will install newest packages versions matching ranges defined in `package.json` instead of versions verified to work and locked in `package-lock.json`.

There is however `yarn.lock` file in the repo, and when using yarn instead of npm build works fine.

Since in the readme instructions are using npm but in the repo there's `yarn.lock`, there should be probably a decision made on which one (npm or yarn) is recomended and then the readme and/or lock files should be updated accordingly.

**Comment by bepitulaz** [comment]
@wotnak thank you. We'll use NPM then. To reduce the step to build the project. Apparently, not everybody knows how to install Yarn and NPM is the default dependency manager for Node.
