### ISSUE TITLE
npm error "node build.js" nodent-runtime

### ISSUE THREAD

**Issue by bobombolo** [Tanibox/tania-core#6]
<pre>
npm ERR! Linux 4.13.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! nodent-runtime@3.2.1 install: `node build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the nodent-runtime@3.2.1 install script 'node build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodent-runtime package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodent-runtime
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodent-runtime
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
</pre>

here are a few lines above this from the debug log
<pre>
389603 warn optional Skipping failed optional dependency /chokidar/fsevents:
389604 warn notsup Not compatible with your operating system or architecture: fsevents@1.1.3
389605 warn optional Skipping failed optional dependency /watchpack/chokidar/fsevents:
389606 warn notsup Not compatible with your operating system or architecture: fsevents@1.1.3
389607 warn optional Skipping failed optional dependency /webpack-dev-server/chokidar/fsevents:
389608 warn notsup Not compatible with your operating system or architecture: fsevents@1.1.3
389609 warn ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none was installed.
389610 verbose stack Error: nodent-runtime@3.2.1 install: `node build.js`
389610 verbose stack spawn ENOENT
389610 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
389610 verbose stack     at emitTwo (events.js:87:13)
389610 verbose stack     at ChildProcess.emit (events.js:172:7)
389610 verbose stack     at maybeClose (internal/child_process.js:821:16)
389610 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
389611 verbose pkgid nodent-runtime@3.2.1
</pre>

**Comment by bobombolo** [comment]
sorry i am totally new to npm, anyway i installed ajv via `npm install ajv` from the project root and reran `npm install` to update ajv from v5 to v6.4
was that the appropriate thing to do? anyway i got the same error, so I think the ajv dependency was a red herring especially since now it is listed in the tree as "extraneous"
however, this time i also noticed at the very top of the output:
<pre>
npm install

> nodent-runtime@3.2.1 install /home/me/go/src/github.com/Tanibox/tania-core/node_modules/nodent-runtime .0
> node build.js

sh: 1: node: not found
/home/me/go/src/github.com/Tanibox/tania-core

</pre>

**Comment by bobombolo** [comment]
OK turns out in my distro i have to install a package called `nodejs-legacy`, i assumed if npm worked then node would be installed. anyway this can just be a paper trail for others running ubuntu/mint etc.

is there any issue with missing the optional dependency `fsevents`?
