### ISSUE TITLE
nmp run dev fails re: webpack.js

### ISSUE THREAD

**Issue by bobombolo** [Tanibox/tania-core#7]
OK, so now on the step of `npm run dev` in the install process and have hit this error:

<pre>
npm run dev

> @ dev /home/me/go/src/github.com/Tanibox/tania-core
> npm run development

> @ development /home/me/go/src/github.com/Tanibox/tania-core
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

/home/me/go/src/github.com/Tanibox/tania-core/node_modules/laravel-mix/setup/webpack.config.js:24
let WebpackConfig = require('../src/builder/WebpackConfig');
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at requireConfig (/home/me/go/src/github.com/Tanibox/tania-core/node_modules/webpack/bin/convert-argv.js:97:18)
    at /home/me/go/src/github.com/Tanibox/tania-core/node_modules/webpack/bin/convert-argv.js:104:17
    at Array.forEach (native)

npm ERR! Linux 4.13.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "development"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ development script 'cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

</pre>

**Comment by adhatama** [comment]
@bobombolo Hi. It looks like your node version is outdated. Yours still node v4.2.6. 
Can you update your node version to at least the LTS version, which is v.8.11.x, and please run `npm install` and `npm run dev` again?

**Comment by bobombolo** [comment]
so i have to go outside my distro's package version?

**Comment by adhatama** [comment]
@bobombolo You can use [nvm](https://github.com/creationix/nvm) to easily switch your node version

**Comment by bobombolo** [comment]
for the benefit of other ubuntu / mint users following my progress, i opted for this method:
`curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -`
`sudo apt-get install -y nodejs`
but first i removed that `nodejs-legacy` package

anyway i reran `npm install` and it went way faster and with less verbose output but fyi still got the warnings about missing peer dependency `ajv` and missing optional dependency `fsevents`

i reran `npm run dev` and got 10 errors with a massive amount of feedback

<pre>
54% building modules 374/375 modules 1 active ...ox/tania-core/resources/sass/a 95% emittingSkipping static resource "public/js/vendor.d16de1bf4a17da55b7f6.js" (3.07 MB) - max size is 2.1 MB
Total precache size is about 5.9 MB for 42 resources.


 ERROR  Failed to compile with 10 errors                                07:36:22

 error  in ./resources/sass/app.scss

Module build failed: Error: ENOENT: no such file or directory, scandir '/home/me/go/src/github.com/Tanibox/tania-core/node_modules/node-sass/vendor'
</pre>
and then a debug stack and then 9 more errors related to missing files including:
<pre>
 error  in ./resources/js/pages/intro/farm.vue

Module build failed: Error: ENOENT: no such file or directory, scandir '/home/me/go/src/github.com/Tanibox/tania-core/node_modules/node-sass/vendor'

 error  in ./resources/js/components/mapbox.vue

Module build failed: Error: ENOENT: no such file or directory, scandir '/home/me/go/src/github.com/Tanibox/tania-core/node_modules/node-sass/vendor'


 error  in ./resources/images/no-img.png

Module build failed: Error: spawn /home/me/go/src/github.com/Tanibox/tania-core/node_modules/optipng-bin/vendor/optipng ENOENT


 error  in ./resources/images/logo.png

Module build failed: Error: spawn /home/me/go/src/github.com/Tanibox/tania-core/node_modules/optipng-bin/vendor/optipng ENOENT


 error  in ./resources/images/logobig.png

Module build failed: Error: spawn /home/me/go/src/github.com/Tanibox/tania-core/node_modules/optipng-bin/vendor/optipng ENOENT


 error  in ./resources/images/marker-shadow.png

Module build failed: Error: spawn /home/me/go/src/github.com/Tanibox/tania-core/node_modules/optipng-bin/vendor/optipng ENOENT


 error  in ./resources/images/marker-icon.png

Module build failed: Error: spawn /home/me/go/src/github.com/Tanibox/tania-core/node_modules/optipng-bin/vendor/optipng ENOENT


error  in ./resources/images/marker-icon-2x.png

Module build failed: Error: spawn /home/me/go/src/github.com/Tanibox/tania-core/node_modules/optipng-bin/vendor/optipng ENOENT

  error  in ./resources/sass/app.scss

Module build failed: ModuleBuildError: Module build failed: Error: ENOENT: no such file or directory, scandir '/home/me/go/src/github.com/Tanibox/tania-core/node_modules/node-sass/vendor'



</pre>
